-- initialize sakila
USE sakila;

-- 1. List the number of films per category.
-- we need film_id col from film_category tbl & name col from category tbl; Com col is category_id
SELECT c.name, COUNT(fc.film_id) AS 'number of films' FROM sakila.category AS c
JOIN film_category as fc
ON c.category_id = fc.category_id
GROUP BY c.name;


-- 2. Retrieve the store ID, city, and country for each store.
-- we need col store_id from store tbl
-- join address tbl com col is address_id with store tbl
-- city col from city tbl com col is city_id with address tbl
-- country col from country tbl com col is country_id
SELECT s.store_id, cty.city, c.country FROM sakila.store AS s
JOIN sakila.address AS a
ON s.address_id = a.address_id
JOIN sakila.city AS cty
ON a.city_id = cty.city_id
JOIN sakila.country AS c
ON cty.country_id = c.country_id;


-- 3. Calculate the total revenue generated by each store in dollars.
-- revenue = sales x avg sales price 
-- ...rental_id = num of rented film & amount = how much that rental cost
-- ...revenue = COUNT(rental_id) x AVG(amount)
-- we need rental_id & amount col from payment tbl & store_id col from staff tbl
-- they connect on staff_id
SELECT s.store_id, round(COUNT(p.rental_id) * AVG(p.amount)) AS 'revenue' FROM sakila.payment AS p
JOIN staff AS s
ON p.staff_id = s.staff_id
GROUP BY s.store_id;


-- 4. Determine the average running time of films for each category.
-- we need the length col from film tbl & name from category tbl
-- the need the film_category tbl to join
SELECT c.name, CEILING(AVG(f.length)) AS 'avg running time' FROM sakila.category AS c
JOIN film_category AS fc
ON c.category_id = fc.category_id
JOIN film AS f
ON fc.film_id = f.film_id
GROUP BY c.name;
